-- Seed sample properties in London area
INSERT INTO public.properties (
  title, address, postcode, city, latitude, longitude, 
  price_pcm, property_type, hmo_type, bedrooms, bathrooms,
  has_garden, is_furnished, is_student_friendly, wifi_included,
  near_tube_station, available_from, description, image_url
) VALUES
(
  'Modern Shared House - Wawlshan',
  '3000, Soun Intermod, Wawlshan',
  'SW1A 1AA',
  'London',
  51.5074,
  -0.1278,
  4500.00,
  'HMO',
  'Licensed HMO',
  6,
  2,
  true,
  true,
  true,
  true,
  true,
  CURRENT_DATE + INTERVAL '7 days',
  'Spacious 6-bedroom HMO property in prime London location. Fully furnished with modern amenities, perfect for professionals or students.',
  '/modern-house-exterior.png'
),
(
  'Luxury Student House',
  '125 Oxford Street',
  'W1D 2HY',
  'London',
  51.5155,
  -0.1428,
  5200.00,
  'House',
  'Standard HMO',
  8,
  3,
  false,
  true,
  true,
  true,
  true,
  CURRENT_DATE + INTERVAL '14 days',
  'Premium 8-bedroom house ideal for students. Walking distance to universities and tube station.',
  '/house-1.jpg'
),
(
  'City Centre Flat Share',
  '45 King Cross Road',
  'WC1X 9DT',
  'London',
  51.5304,
  -0.1167,
  3800.00,
  'Flat',
  'Potential HMO',
  5,
  2,
  false,
  true,
  true,
  true,
  true,
  CURRENT_DATE,
  'Bright and spacious flat in the heart of King Cross. Excellent transport links.',
  '/house-2.jpg'
),
(
  'Victorian House Share',
  '89 Camden High Street',
  'NW1 7JY',
  'London',
  51.5392,
  -0.1426,
  4200.00,
  'House',
  'Licensed HMO',
  7,
  2,
  true,
  true,
  false,
  true,
  true,
  CURRENT_DATE + INTERVAL '21 days',
  'Beautiful Victorian property converted into modern HMO. Garden access and all bills included.',
  '/house-3.jpg'
),
(
  'Riverside Apartment',
  '12 Thames Path',
  'SE1 9PX',
  'London',
  51.5033,
  -0.1195,
  4800.00,
  'Flat',
  'Standard HMO',
  6,
  2,
  false,
  true,
  true,
  true,
  false,
  CURRENT_DATE + INTERVAL '10 days',
  'Stunning riverside views from this modern 6-bed apartment. Perfect for professionals.',
  '/modern-shared-house-property.jpg'
);

-- Add more properties around London to populate the map
INSERT INTO public.properties (
  title, address, postcode, city, latitude, longitude,
  price_pcm, property_type, hmo_type, bedrooms, bathrooms,
  has_garden, is_furnished, is_student_friendly, wifi_included,
  near_tube_station, available_from
) VALUES
('North London House', '78 Finsbury Park Road', 'N4 2JX', 'London', 51.5642, -0.1065, 3900, 'House', 'Licensed HMO', 5, 2, true, true, true, true, true, CURRENT_DATE),
('East End Flat', '234 Bethnal Green Road', 'E2 0AA', 'London', 51.5273, -0.0559, 3500, 'Flat', 'Standard HMO', 4, 1, false, true, false, true, true, CURRENT_DATE),
('West London Property', '56 Shepherd Bush Road', 'W6 7PH', 'London', 51.5033, -0.2217, 4100, 'House', 'Potential HMO', 6, 2, true, true, true, true, true, CURRENT_DATE),
('South London Share', '145 Clapham High Street', 'SW4 7SS', 'London', 51.4618, -0.1384, 3700, 'Flat', 'Licensed HMO', 5, 2, false, true, true, true, true, CURRENT_DATE),
('Greenwich House', '92 Greenwich Park Street', 'SE10 8QY', 'London', 51.4826, 0.0077, 3600, 'House', 'Standard HMO', 5, 2, true, true, false, true, false, CURRENT_DATE),
('Hackney Apartment', '167 Mare Street', 'E8 3RH', 'London', 51.5456, -0.0553, 4000, 'Flat', 'Licensed HMO', 6, 2, false, true, true, true, true, CURRENT_DATE),
('Islington Property', '88 Upper Street', 'N1 0NP', 'London', 51.5416, -0.1030, 4300, 'House', 'Standard HMO', 7, 3, true, true, true, true, true, CURRENT_DATE),
('Brixton House Share', '203 Brixton Hill', 'SW2 1RB', 'London', 51.4514, -0.1167, 3800, 'House', 'Potential HMO', 5, 2, true, true, true, true, true, CURRENT_DATE),
('Shoreditch Loft', '45 Great Eastern Street', 'EC2A 3EP', 'London', 51.5254, -0.0831, 5000, 'Flat', 'Licensed HMO', 6, 2, false, true, false, true, true, CURRENT_DATE),
('Notting Hill House', '78 Portobello Road', 'W11 2DZ', 'London', 51.5165, -0.2053, 5500, 'House', 'Licensed HMO', 8, 3, true, true, true, true, true, CURRENT_DATE);
